# Generated by Django 3.0.8 on 2020-07-17 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marks',
            old_name='mark',
            new_name='marks',
        ),
    ]
