# Generated by Django 3.0.8 on 2020-07-17 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 17, 13, 46, 36, 356533)),
        ),
    ]
