# Generated by Django 3.0.8 on 2020-07-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200717_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='marks',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='max_marks',
            field=models.FloatField(),
        ),
    ]
